// apiConstants.js
const PLEDGE_ITEM_BASE = '/pledge-item';

export const pledgeItemsEndpoints = {
  CREATE: `${PLEDGE_ITEM_BASE}/`,
  READBYID: `${PLEDGE_ITEM_BASE}/:id`,
  READALLLIST:  `${PLEDGE_ITEM_BASE}/pledge_all`,
  READALL: (page, limit) => `${PLEDGE_ITEM_BASE}/${page}/${limit}/${localStorage.getItem("userId")}`,
  READOFFIEALL: (page, limit) => `${PLEDGE_ITEM_BASE}/executive/${page}/${limit}/${localStorage.getItem("userId")}`,
  READMONEYREQUESTALL: (page, limit) => `${PLEDGE_ITEM_BASE}/money_request/${page}/${limit}/${localStorage.getItem("userId")}`,
  READMANGERALL: (page, limit) => `${PLEDGE_ITEM_BASE}/manager/${page}/${limit}/${localStorage.getItem("userId")}`,
  READMANGERALL1: (page, limit) => `${PLEDGE_ITEM_BASE}/manager_first/${page}/${limit}/${localStorage.getItem("userId")}`,
  READREGIONALMANGERALL: (page, limit) => `${PLEDGE_ITEM_BASE}/regional_manager/${page}/${limit}/${localStorage.getItem("userId")}`,
  READACCOUNTSAPPROVALALL: (page, limit) => `${PLEDGE_ITEM_BASE}/accounts_approval/${page}/${limit}/${localStorage.getItem("userId")}`,
  READACCOUNTSALL: (page, limit) => `${PLEDGE_ITEM_BASE}/accounts/${page}/${limit}/${localStorage.getItem("userId")}`,
  READCOLLECTIONALL: (page, limit) => `${PLEDGE_ITEM_BASE}/collection/${page}/${limit}/${localStorage.getItem("userId")}`,
  READBANKCOLLECTIONALL: (page, limit) => `${PLEDGE_ITEM_BASE}/bank_collection/${page}/${limit}/${localStorage.getItem("userId")}`,
  READFINANCEINSTITUTEALL: (page, limit) => `${PLEDGE_ITEM_BASE}/finance_institute/${page}/${limit}/${localStorage.getItem("userId")}`,
  READGOLDCOLLECTALL: (page, limit) => `${PLEDGE_ITEM_BASE}/gold_collect/${page}/${limit}/${localStorage.getItem("userId")}`,
  READMANAGERAPPROVEALL: (page, limit) => `${PLEDGE_ITEM_BASE}/manager_approvals/${page}/${limit}/${localStorage.getItem("userId")}`,
  UPDATE: `${PLEDGE_ITEM_BASE}/:id`,
  DELETE: `${PLEDGE_ITEM_BASE}/:id`,
  SEARCH: `${PLEDGE_ITEM_BASE}/search`,
  EXECUTIVE: `${PLEDGE_ITEM_BASE}/executive/${localStorage.getItem("userId")}`,
  MANAGER: `${PLEDGE_ITEM_BASE}/manager`,
  ASSIGN: `${PLEDGE_ITEM_BASE}/assign/:id`,
  ASSIGN_SALES_EXECUTIVE:`${PLEDGE_ITEM_BASE}/assign_sales_executive/:id`,
  ASSIGNRegional: `${PLEDGE_ITEM_BASE}/assign_regional/:id`,
  ACCOUNTSAPPROVAL_REQUEST: `${PLEDGE_ITEM_BASE}/accounts_approval/:id`,
  STATUS: `${PLEDGE_ITEM_BASE}/status/:id`,
  GET_BY_ROLE: `${PLEDGE_ITEM_BASE}/by-role/:roleId`,
  MONEY_REQUEST:`${PLEDGE_ITEM_BASE}/money_request/:id`,
  ACCOUNTS_REQUEST:`${PLEDGE_ITEM_BASE}/accounts/:id`,
  COLLECTION_REQUEST:`${PLEDGE_ITEM_BASE}/collection/:id`,
  BANK_COLLECTION_REQUEST:`${PLEDGE_ITEM_BASE}/bank_collection/:id`,
  FINANCE_INSTITUTE_REQUEST:`${PLEDGE_ITEM_BASE}/finance_institute/:id`,
  GOLD_COLLECT_REQUEST:`${PLEDGE_ITEM_BASE}/gold_collect/:id`,
  MANAGERAPPROVALREQUEST:`${PLEDGE_ITEM_BASE}/manager_approvals/:id`,
  MANGER_APPROVAL_REQUEST:`${PLEDGE_ITEM_BASE}/manager_approval/:id`
};